### ISSUE TITLE
Duplicate margin property in rmodal-no-bootstrap.css

### ISSUE THREAD

**Issue by not-a-lot** [zewish/rmodal.js#13]
In rmodal version 1.0.28, the `margin` property in `
.modal .modal-dialog` in the file `rmodal-no-bootstrap.css` is duplicated :
```css
.modal .modal-dialog {
    position: relative;
    margin: 30px auto;
    …
    margin: 0 auto;
}
```
